name: Coding Standard

on:
  push:
    branches:
      - 2.[0-9]-develop
  pull_request:
    branches:
      - 2.[0-9]-develop

jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install

      - name: Register Coding Standard
        run: vendor/bin/phpcs --config-set installed_paths vendor/magento/magento-coding-standard

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3

      - name: Coding Standard Check
        run: vendor/bin/phpcs --standard=Magento2 ${{ steps.changed-files.outputs.all_changed_files }}
