name: Coding Standard

on:
  pull_request:
    branches:
      - 2.4-develop

jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Coding Standard
        uses: danslo/github-actions-magento2/coding-standard@main
