on:
  push:
    branches:
      - '**'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: magento2

      - uses: actions/checkout@v3
        with:
          repository: davidalger/warden
          ref: master
          path: warden

      - run: echo "$GITHUB_WORKSPACE/warden/bin" >> $GITHUB_PATH
      - run: warden svc up

      - run: warden env up
        working-directory: magento2
