on:
  push:
    branches:
      - '**'

env:
  TRAEFIK_DOMAIN: 'magento2.test'
  TRAEFIK_SUBDOMAIN: 'app'

jobs:
  e2e:
    runs-on: self-hosted
    steps:
      - name: Run Cypress
        run: echo $CYPRESS_MAGENTO2_BASE_URL
        env:
          CYPRESS_MAGENTO2_BASE_URL: 'https://${{ env.TRAEFIK_SUBDOMAIN }}.${{ env.TRAEFIK_DOMAIN }}/'
