on:
  push:
    branches:
      - '**'

env:
  TRAEFIK_DOMAIN: 'magento2.test'
  TRAEFIK_SUBDOMAIN: 'app'

jobs:
  e2e:
    runs-on: self-hosted
    steps:
      - name: Checkout Magento
        uses: actions/checkout@v3
        with:
          path: magento2
          ref: 2.4.5
          repository: magento/magento2

      - name: Checkout Warden
        uses: actions/checkout@v3
        with:
          repository: davidalger/warden
          ref: master
          path: warden

      - name: Checkout Cypress Testing Suite
        uses: actions/checkout@v3
        with:
          repository: elgentos/magento2-cypress-testing-suite
          ref: main
          path: cypress-testing-suite

      - name: Checkout Sample Data
        uses: actions/checkout@v3
        with:
          repository: magento/magento2-sample-data
          ref: 2.4-develop # todo, use current branch name
          path: magento2/sample-data

      - name: Setup Warden
        run: echo "$GITHUB_WORKSPACE/warden/bin" >> $GITHUB_PATH

      - name: Initialize Warden
        run: warden svc up

      - name: Sign Certificate
        run: warden sign-certificate ${TRAEFIK_DOMAIN}

      - name: Initialize Environment
        run: warden env up
        working-directory: magento2

      - name: Add Hosts Entry
        run: echo "127.0.0.1 ${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}" | sudo tee -a /etc/hosts

      - name: Set Permissions
        run: sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE/magento2

      - name: Update User and Group IDs
        shell: 'script -q -e -c "bash {0}"'
        run: |
          warden env exec php-fpm sudo groupmod -g $(id -g) www-data
          warden env exec php-fpm sudo usermod -u $(id -u) www-data
        working-directory: magento2

      - name: Composer Install
        shell: 'script -q -e -c "bash {0}"'
        run: warden env exec php-fpm composer install
        working-directory: magento2

      - name: Install Magento
        shell: 'script -q -e -c "bash {0}"'
        run: >
          warden env exec php-fpm bin/magento setup:install \
              --backend-frontname=backend \
              --amqp-host=rabbitmq \
              --amqp-port=5672 \
              --amqp-user=guest \
              --amqp-password=guest \
              --db-host=db \
              --db-name=magento \
              --db-user=magento \
              --db-password=magento \
              --search-engine=elasticsearch7 \
              --elasticsearch-host=elasticsearch \
              --elasticsearch-port=9200 \
              --elasticsearch-index-prefix=magento2 \
              --elasticsearch-enable-auth=0 \
              --elasticsearch-timeout=15 \
              --http-cache-hosts=varnish:80 \
              --session-save=redis \
              --session-save-redis-host=redis \
              --session-save-redis-port=6379 \
              --session-save-redis-db=2 \
              --session-save-redis-max-concurrency=20 \
              --cache-backend=redis \
              --cache-backend-redis-server=redis \
              --cache-backend-redis-db=0 \
              --cache-backend-redis-port=6379 \
              --page-cache=redis \
              --page-cache-redis-server=redis \
              --page-cache-redis-db=1 \
              --page-cache-redis-port=6379
        working-directory: magento2

      - name: Install Sample Data
        shell: 'script -q -e -c "bash {0}"'
        run: warden env exec php-fpm php -f sample-data/dev/tools/build-sample-data.php -- --ce-source="/var/www/html"
        working-directory: magento2

      - name: Setup Upgrade
        shell: 'script -q -e -c "bash {0}"'
        run: warden env exec php-fpm bin/magento setup:upgrade
        working-directory: magento2

      - name: Update Configuration
        shell: 'script -q -e -c "bash {0}"'
        run: |
          warden env exec php-fpm bin/magento config:set --lock-env web/unsecure/base_url "https://${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}/"
          warden env exec php-fpm bin/magento config:set --lock-env web/secure/base_url "https://${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}/"
          warden env exec php-fpm bin/magento config:set --lock-env web/secure/offloader_header X-Forwarded-Proto
          warden env exec php-fpm bin/magento config:set --lock-env web/secure/use_in_frontend 1
          warden env exec php-fpm bin/magento config:set --lock-env web/secure/use_in_adminhtml 1
          warden env exec php-fpm bin/magento config:set --lock-env web/seo/use_rewrites 1
          warden env exec php-fpm bin/magento config:set --lock-env system/full_page_cache/caching_application 2
          warden env exec php-fpm bin/magento config:set --lock-env system/full_page_cache/ttl 604800
          warden env exec php-fpm bin/magento config:set --lock-env catalog/search/enable_eav_indexer 1
          warden env exec php-fpm bin/magento config:set --lock-env dev/static/sign 0
        working-directory: magento2

      - name: Reindex
        shell: 'script -q -e -c "bash {0}"'
        run: warden env exec php-fpm bin/magento indexer:reindex
        working-directory: magento2

      - name: Create Admin User
        shell: 'script -q -e -c "bash {0}"'
        run: >
          warden env exec php-fpm n98-magerun admin:user:create \
            --admin-user=john \
            --admin-firstname=John \
            --admin-lastname=Doe \
            --admin-password=JohnDoe123 \
            --admin-email="john@example.com"
        working-directory: magento2

      - name: Create Integration Token
        id: create_token
        shell: 'script -q -e -c "bash {0}"'
        run: |
          mv vendor/symfony/console vendor/symfony/console.bak
          rm -rf generated/*
          echo "::set-output name=token::$(warden env exec php-fpm n98-magerun admin:token:create john)"
          mv vendor/symfony/console.bak vendor/symfony/console
        working-directory: magento2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cypress
        run: npm install cypress cypress-file-upload cypress-localstorage-commands cypress-tags typescript --save-dev
        working-directory: cypress-testing-suite

      - name: Remove Hyva Tests
        run: rm -rf cypress/{fixtures,page-objects,integration}/hyva
        working-directory: cypress-testing-suite

      - name: Run Cypress
        run: npx cypress run
        working-directory: cypress-testing-suite
        env:
          CYPRESS_MAGENTO2_BASE_URL: https://${{ env.TRAEFIK_SUBDOMAIN }}.${{ env.TRAEFIK_DOMAIN }}/
          CYPRESS_MAGENTO2_ADMIN_TOKEN: ${{ steps.create_token.outputs.token }}
