on:
  push:
    branches:
      - '**' # TODO: remove
  pull_request:
    branches:
      - '**'

jobs:
  notify-discord:
    name: "Notify Discord"
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      #- uses: kceb/pull-request-url-action@v1
      #  id: pr-url

      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: "Mage-OS"
          DISCORD_EMBEDS: >
            [
              {
                "title": "PR title",
                "description": "PR content",
                "url": "",
                "color": ffffff,
                "thumbnail": {
                  "url": "https://cdn.discordapp.com/embed/avatars/0.png"
                },
                "author": {
                  "name": "author name",
                  "url": "https://discordapp.com",
                  "icon_url": "https://cdn.discordapp.com/embed/avatars/0.png"
                }
              }
            ]
